<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enlaces a Carpetas</title>
    <link rel="stylesheet" href="estilos.css">
</head>
<body>
    <div class="contenedor bg_celeste">
    <h1>Sistema de Gestion</h1>
    <h2 >ALUMNOS</h2>
    <a href="CRUD_Alumno/read.php" style="color:black">CLICK:Alumnos</a>
    <br>
    <H2>CARRERAS</H2>
    <a href="CRUD_Carrera/readC.php" style="color:black">CLICK:Carreras</a>
    </div>
</body>
</html>
